<?php

$helper = __DIR__ . '/../docker/PostgresBootstrap.php';
if (!is_file($helper)) {
    throw new RuntimeException('PostgresBootstrap helper is missing');
}
require_once $helper;

$host = getenv('DB_HOST') ?: 'db';
$port = getenv('DB_PORT') ?: '5432';
$name = getenv('DB_NAME') ?: 'epay';
$user = getenv('DB_USER') ?: 'epay';
$password = getenv('DB_PASSWORD') ?: '';
$table = 'test_user_identity_' . bin2hex(random_bytes(6));

$pdo = new PDO("pgsql:host={$host};port={$port};dbname={$name}", $user, $password, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

$pdo->exec('CREATE TABLE "'.$table.'" ("uid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)');

try {
    PostgresBootstrap::ensureEmptyIdentityStartsAt($pdo, $table, 'uid', 1000);
    $first = $pdo->query('INSERT INTO "'.$table.'" DEFAULT VALUES RETURNING "uid"')->fetchColumn();
    if ((int)$first !== 1000) {
        throw new RuntimeException('Expected first merchant UID 1000, got '.$first);
    }

    PostgresBootstrap::ensureEmptyIdentityStartsAt($pdo, $table, 'uid', 1000);
    $second = $pdo->query('INSERT INTO "'.$table.'" DEFAULT VALUES RETURNING "uid"')->fetchColumn();
    if ((int)$second !== 1001) {
        throw new RuntimeException('Non-empty table identity was reset unexpectedly');
    }
} finally {
    $pdo->exec('DROP TABLE IF EXISTS "'.$table.'"');
}

echo "PostgreSQL user identity test passed.\n";

