<?php

$migrationFile = __DIR__.'/../docker/PostgresMigrations.php';
if (!is_file($migrationFile)) {
	throw new RuntimeException('PostgresMigrations helper is missing.');
}
require_once $migrationFile;

function assertSchemaUpgrade($condition, $message)
{
	if (!$condition) throw new RuntimeException($message);
}

function quoteSchemaIdentifier($identifier)
{
	return '"'.str_replace('"', '""', $identifier).'"';
}

function dropPrefixTables(PDO $pdo, $prefix)
{
	$stmt = $pdo->prepare("SELECT tablename FROM pg_tables WHERE schemaname=current_schema() AND tablename LIKE :pattern");
	$stmt->execute([':pattern'=>$prefix.'\_%']);
	foreach ($stmt->fetchAll(PDO::FETCH_COLUMN) as $table) {
		$pdo->exec('DROP TABLE IF EXISTS '.quoteSchemaIdentifier($table).' CASCADE');
	}
}

function columnExists(PDO $pdo, $table, $column)
{
	$stmt = $pdo->prepare('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=:table AND column_name=:column');
	$stmt->execute([':table'=>$table, ':column'=>$column]);
	return (int)$stmt->fetchColumn() === 1;
}

$host = getenv('DB_HOST') ?: 'db';
$port = getenv('DB_PORT') ?: '5432';
$name = getenv('DB_NAME');
$user = getenv('DB_USER');
$password = getenv('DB_PASSWORD');
$pdo = new PDO("pgsql:host={$host};port={$port};dbname={$name}", $user, $password, [
	PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,
]);

$prefix = 'upgrade_'.bin2hex(random_bytes(4));
$failurePrefix = 'upgrade_fail_'.bin2hex(random_bytes(4));
$installSql = file_get_contents(__DIR__.'/../install/install.sql');

try {
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_config').' (k VARCHAR(32) PRIMARY KEY, v TEXT)');
	$pdo->exec("INSERT INTO ".quoteSchemaIdentifier($prefix.'_config')." (k,v) VALUES ('version','2043')");
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_cache').' (k VARCHAR(32) PRIMARY KEY, v TEXT, expire BIGINT NOT NULL DEFAULT 0)');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_order').' (trade_no CHAR(19) PRIMARY KEY, status SMALLINT NOT NULL DEFAULT 0)');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_user').' (uid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "key" VARCHAR(32) NOT NULL, money DECIMAL(10,2) NOT NULL)');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_plugin').' (name VARCHAR(30) PRIMARY KEY, types VARCHAR(30), transtypes VARCHAR(30))');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_type').' (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(20), device SMALLINT, showname VARCHAR(20), status SMALLINT)');

	PostgresMigrations::upgradeToCurrent($pdo, $prefix, $installSql);

	foreach (['transfer','refundorder','psreceiver','psorder','subchannel','suborder'] as $table) {
		assertSchemaUpgrade((bool)$pdo->query("SELECT to_regclass(".$pdo->quote($prefix.'_'.$table).")")->fetchColumn(), 'Missing upgraded table '.$table.'.');
	}
	foreach ([
		[$prefix.'_order', 'subchannel'],
		[$prefix.'_order', 'notifytime'],
		[$prefix.'_order', 'bill_mch_trade_no'],
		[$prefix.'_order', 'cert_info'],
		[$prefix.'_order', 'province'],
		[$prefix.'_user', 'voice_order'],
		[$prefix.'_user', 'print_config'],
		[$prefix.'_channel', 'daymaxorder'],
		[$prefix.'_transfer', 'out_biz_no'],
		[$prefix.'_psorder', 'retry'],
	] as $expected) {
		assertSchemaUpgrade(columnExists($pdo, $expected[0], $expected[1]), 'Missing upgraded column '.$expected[0].'.'.$expected[1].'.');
	}
	$version = $pdo->query("SELECT v FROM ".quoteSchemaIdentifier($prefix.'_config')." WHERE k='version'")->fetchColumn();
	assertSchemaUpgrade((int)$version === PostgresMigrations::CURRENT_VERSION, 'Successful upgrade must set the current version.');

	PostgresMigrations::upgradeToCurrent($pdo, $prefix, $installSql);
	$versionAfterRetry = $pdo->query("SELECT v FROM ".quoteSchemaIdentifier($prefix.'_config')." WHERE k='version'")->fetchColumn();
	assertSchemaUpgrade((int)$versionAfterRetry === PostgresMigrations::CURRENT_VERSION, 'Repeated upgrades must remain idempotent.');

	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($failurePrefix.'_config').' (k VARCHAR(32) PRIMARY KEY, v TEXT)');
	$pdo->exec("INSERT INTO ".quoteSchemaIdentifier($failurePrefix.'_config')." (k,v) VALUES ('version','2043')");
	$brokenSql = $installSql."\nCREATE TABLE `pre_broken` (`id` invalid_postgres_type NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;";
	$failed = false;
	try {
		PostgresMigrations::upgradeToCurrent($pdo, $failurePrefix, $brokenSql);
	} catch (Throwable $e) {
		$failed = true;
	}
	assertSchemaUpgrade($failed, 'An invalid migration must fail.');
	$failedVersion = $pdo->query("SELECT v FROM ".quoteSchemaIdentifier($failurePrefix.'_config')." WHERE k='version'")->fetchColumn();
	assertSchemaUpgrade((int)$failedVersion === 2043, 'A failed migration must not advance the database version.');

	echo "PostgreSQL schema upgrade tests passed.\n";
} finally {
	if ($pdo->inTransaction()) $pdo->rollBack();
	dropPrefixTables($pdo, $prefix);
	dropPrefixTables($pdo, $failurePrefix);
}
