<?php

$migrationFile = __DIR__.'/../docker/PostgresMigrations.php';
if (!is_file($migrationFile)) {
	throw new RuntimeException('PostgresMigrations helper is missing.');
}
require_once $migrationFile;

function assertSchemaUpgrade($condition, $message)
{
	if (!$condition) throw new RuntimeException($message);
}

function quoteSchemaIdentifier($identifier)
{
	return '"'.str_replace('"', '""', $identifier).'"';
}

function dropPrefixTables(PDO $pdo, $prefix)
{
	$stmt = $pdo->prepare("SELECT tablename FROM pg_tables WHERE schemaname=current_schema() AND tablename LIKE :pattern");
	$stmt->execute([':pattern'=>$prefix.'\_%']);
	foreach ($stmt->fetchAll(PDO::FETCH_COLUMN) as $table) {
		$pdo->exec('DROP TABLE IF EXISTS '.quoteSchemaIdentifier($table).' CASCADE');
	}
}

function columnExists(PDO $pdo, $table, $column)
{
	$stmt = $pdo->prepare('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=:table AND column_name=:column');
	$stmt->execute([':table'=>$table, ':column'=>$column]);
	return (int)$stmt->fetchColumn() === 1;
}

function columnType(PDO $pdo, $table, $column)
{
	$stmt = $pdo->prepare('SELECT data_type, character_maximum_length FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=:table AND column_name=:column');
	$stmt->execute([':table'=>$table, ':column'=>$column]);
	return $stmt->fetch(PDO::FETCH_ASSOC);
}

function hasIndexColumns(PDO $pdo, $table, array $columns, $unique = false)
{
	$stmt = $pdo->prepare(
		'SELECT i.indisunique, array_agg(a.attname ORDER BY keys.ordinality) AS columns '.
		'FROM pg_index i '.
		'JOIN pg_class t ON t.oid=i.indrelid '.
		'JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS keys(attnum, ordinality) ON true '.
		'JOIN pg_attribute a ON a.attrelid=t.oid AND a.attnum=keys.attnum '.
		'WHERE t.relname=:table GROUP BY i.indexrelid, i.indisunique'
	);
	$stmt->execute([':table'=>$table]);
	foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $index) {
		$actual = trim((string)$index['columns'], '{}');
		if (explode(',', $actual) === $columns && (!$unique || $index['indisunique'])) return true;
	}
	return false;
}

$host = getenv('DB_HOST') ?: 'db';
$port = getenv('DB_PORT') ?: '5432';
$name = getenv('DB_NAME');
$user = getenv('DB_USER');
$password = getenv('DB_PASSWORD');
$pdo = new PDO("pgsql:host={$host};port={$port};dbname={$name}", $user, $password, [
	PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,
]);

$prefix = 'upgrade_'.bin2hex(random_bytes(4));
$failurePrefix = 'upgrade_fail_'.bin2hex(random_bytes(4));
$installSql = file_get_contents(__DIR__.'/../install/install.sql');
$initSource = file_get_contents(__DIR__.'/../docker/init-postgres.php');

assertSchemaUpgrade(
	strpos($initSource, 'if ($version >= PostgresMigrations::CURRENT_VERSION) return;') === false,
	'Container startup must reconcile schemas even when a previously broken upgrade already wrote the current version.'
);

try {
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_config').' (k VARCHAR(32) PRIMARY KEY, v TEXT)');
	$pdo->exec("INSERT INTO ".quoteSchemaIdentifier($prefix.'_config')." (k,v) VALUES ('version','2043')");
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_cache').' (k VARCHAR(32) PRIMARY KEY, v TEXT, expire BIGINT NOT NULL DEFAULT 0)');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_order').' (trade_no CHAR(19) PRIMARY KEY, status SMALLINT NOT NULL DEFAULT 0)');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_user').' (uid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "key" VARCHAR(32) NOT NULL, money DECIMAL(10,2) NOT NULL)');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_plugin').' (name VARCHAR(30) PRIMARY KEY, types VARCHAR(30), transtypes VARCHAR(30))');
	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($prefix.'_type').' (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(20), device SMALLINT, showname VARCHAR(20), status SMALLINT)');

	PostgresMigrations::upgradeToCurrent($pdo, $prefix, $installSql);

	foreach (['transfer','refundorder','psreceiver','psorder','subchannel','suborder'] as $table) {
		assertSchemaUpgrade((bool)$pdo->query("SELECT to_regclass(".$pdo->quote($prefix.'_'.$table).")")->fetchColumn(), 'Missing upgraded table '.$table.'.');
	}
	foreach ([
		[$prefix.'_order', 'subchannel'],
		[$prefix.'_order', 'notifytime'],
		[$prefix.'_order', 'bill_mch_trade_no'],
		[$prefix.'_order', 'cert_info'],
		[$prefix.'_order', 'province'],
		[$prefix.'_user', 'voice_order'],
		[$prefix.'_user', 'print_config'],
		[$prefix.'_channel', 'daymaxorder'],
		[$prefix.'_transfer', 'out_biz_no'],
		[$prefix.'_psorder', 'retry'],
	] as $expected) {
		assertSchemaUpgrade(columnExists($pdo, $expected[0], $expected[1]), 'Missing upgraded column '.$expected[0].'.'.$expected[1].'.');
	}
	foreach ([
		[$prefix.'_order', ['bill_mch_trade_no'], false],
		[$prefix.'_transfer', ['out_biz_no', 'uid'], false],
		[$prefix.'_blacklist', ['content', 'type'], true],
	] as $expectedIndex) {
		assertSchemaUpgrade(
			hasIndexColumns($pdo, $expectedIndex[0], $expectedIndex[1], $expectedIndex[2]),
			'Missing upgraded index on '.$expectedIndex[0].' ('.implode(',', $expectedIndex[1]).').'
		);
	}
	foreach ([
		[$prefix.'_plugin', 'types', 'character varying', 500],
		[$prefix.'_plugin', 'transtypes', 'character varying', 500],
		[$prefix.'_user', 'pwd', 'character varying', 255],
		[$prefix.'_user', 'msgconfig', 'text', null],
	] as $expectedType) {
		$actualType = columnType($pdo, $expectedType[0], $expectedType[1]);
		assertSchemaUpgrade($actualType !== false, 'Missing typed column '.$expectedType[0].'.'.$expectedType[1].'.');
		assertSchemaUpgrade($actualType['data_type'] === $expectedType[2], 'Unexpected type for '.$expectedType[0].'.'.$expectedType[1].'.');
		assertSchemaUpgrade($actualType['character_maximum_length'] === $expectedType[3], 'Unexpected length for '.$expectedType[0].'.'.$expectedType[1].'.');
	}
	$typeRows = $pdo->query('SELECT id,name FROM '.quoteSchemaIdentifier($prefix.'_type').' WHERE id IN (6,7) ORDER BY id')->fetchAll(PDO::FETCH_KEY_PAIR);
	assertSchemaUpgrade($typeRows === [6=>'paypal', 7=>'douyinpay'], 'Canonical payment types 6 and 7 were not reconciled.');
	$version = $pdo->query("SELECT v FROM ".quoteSchemaIdentifier($prefix.'_config')." WHERE k='version'")->fetchColumn();
	assertSchemaUpgrade((int)$version === PostgresMigrations::CURRENT_VERSION, 'Successful upgrade must set the current version.');

	PostgresMigrations::upgradeToCurrent($pdo, $prefix, $installSql);
	$versionAfterRetry = $pdo->query("SELECT v FROM ".quoteSchemaIdentifier($prefix.'_config')." WHERE k='version'")->fetchColumn();
	assertSchemaUpgrade((int)$versionAfterRetry === PostgresMigrations::CURRENT_VERSION, 'Repeated upgrades must remain idempotent.');

	$pdo->exec('CREATE TABLE '.quoteSchemaIdentifier($failurePrefix.'_config').' (k VARCHAR(32) PRIMARY KEY, v TEXT)');
	$pdo->exec("INSERT INTO ".quoteSchemaIdentifier($failurePrefix.'_config')." (k,v) VALUES ('version','2043')");
	$brokenSql = $installSql."\nCREATE TABLE `pre_broken` (`id` invalid_postgres_type NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;";
	$failed = false;
	try {
		PostgresMigrations::upgradeToCurrent($pdo, $failurePrefix, $brokenSql);
	} catch (Throwable $e) {
		$failed = true;
	}
	assertSchemaUpgrade($failed, 'An invalid migration must fail.');
	$failedVersion = $pdo->query("SELECT v FROM ".quoteSchemaIdentifier($failurePrefix.'_config')." WHERE k='version'")->fetchColumn();
	assertSchemaUpgrade((int)$failedVersion === 2043, 'A failed migration must not advance the database version.');

	echo "PostgreSQL schema upgrade tests passed.\n";
} finally {
	if ($pdo->inTransaction()) $pdo->rollBack();
	dropPrefixTables($pdo, $prefix);
	dropPrefixTables($pdo, $failurePrefix);
}
